### ISSUE TITLE
Migrate from asyncio-mqtt to aiomqtt

### ISSUE THREAD

**Issue by mweinelt** [MartinHjelmare/aiomysensors#449]
**Describe the bug**
The asyncio-mqtt project has been renamed to [aiomqtt](https://github.com/sbtinstruments/aiomqtt). The old project name receives no updates anymore.

**To Reproduce**
- Observe how https://github.com/sbtinstruments/asyncio-mqtt redirects
- Check https://pypi.org/project/asyncio-mqtt/#history
- Check https://pypi.org/project/aiomqtt/#history

**Additional context**
https://sbtinstruments.github.io/aiomqtt/migration-guide-v2.html

**Comment by MartinHjelmare** [comment]
A PR is welcome. Thanks!
